version: "3"

services:
  nginx:
    container_name: nginx_ore
    image: nginx
    restart: always
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /var/run
      - /var/cache
      - /var/log/nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certs/etc/letsencrypt/live/${DOMAIN}/fullchain.pem:/cert.pem:ro
      - ./certs/etc/letsencrypt/live/${DOMAIN}/privkey.pem:/key.pem:ro
    environment:
      - TZ
    ports:
      - 443:443
      - 80:80
