
version: "3"

services:
  mysql-test:
    image: mysql
    container_name: mysql-ore
    restart: always
    ports:
    - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
     - test_volume:/var/lib/${MYSQL_DATABASE}

  redis-test:
    image: redis
    container_name: redis-ore
    restart: always
    ports:
    - "6379:6379"
    
  backend:
    build:
      context: ./ore
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment: 
      - DOMAIN=k7a504.p.ssafy.io
      - MAIL_USERNAME=oreofficialcontact
      - MAIL_PASSWORD=qwer12!@
      - REGION=ap-northeast-2
      - ACCESS_KEY=AKIAYYKS2KK4MUHS2OXO
      - SECRET_KEY=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
      - BUCKET=ore-s3
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

volumes:
    test_volume:
    
