server:
  servlet:
    contextPath: /
    encoding:
      enabled: "true"
      force: "true"
      charset: UTF-8
  port: "8080"

spring:
  #mail
  mail:
    port: 465
    host: smtp.naver.com
    username: oreofficialcontact
    password: ore1234!@#$
    properties:
      mail:
        debug: true
        transport:
          protocol: smtp
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          ssl:
            enable: true
  redis:
    host: localhost
    port: 6379

  #mysql
  jpa:
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
      use-new-id-generator-mappings: "true"
    properties:
      hibernate:
        format_sql: "true"
        show_sql: "true"
    database: mysql
    show-sql: "true"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
#      password: test504
#      username: oretest
#    url: jdbc:mysql://k7a504.p.ssafy.io:3306/oredb?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      password: ore504%)$
      username: ore504
    url: jdbc:mysql://localhost:3306/ore?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC

  devtools:
    livereload:
      enabled: "true"

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  jackson:
    serialization:
      fail-on-empty-beans: false

#jwt
jwt:
  header: Authorization
  secret: 7JWI64WV7ZWY7IS47JqUIE9SReyEnOu5hOyKpOydmCBTZWNyZXQgS2V57J6F64uI64ukIOygiOuMgCDqs7XsnKDtlZjsp4Drp4jshLjsmpQ=

#S3
cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: AKIAYYKS2KK4MUHS2OXO
      secret-key: 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
    s3:
      bucket: ore-s3
      bucketUrl: https://ore-s3.s3.ap-northeast-2.amazonaws.com/